import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto_Mono = Roboto_Mono({
  variable: '--font-roboto-mono',
  weight: ['500','600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin-ext', 'latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto_Mono.className} h-full antialiased dark` }
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}

      </body>
    </html>
  );
}
